### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by talldan** [testower/forwardslash#1]
Hi,

I tried to use your library by doing the following:
```import / from 'forwardslash';```

and I get this error:
```Uncaught SyntaxError: Invalid regular expression: missing /```

How can I avoid this?

**Comment by testower** [comment]
I'm considering writing a compile-to-js language that will support this. I need suggestions on what to call this language. I have so far FlashScript.
